name: template-sync

on:
  # cronjob trigger at 03:00 every day.
  schedule:
  - cron:  "0 3 * * *"
  # manual trigger
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v0.4.0-draft
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_repo_path: ventx/stackx-template-terraform
          pr_labels: chore,template-sync
